FROM node:22-alpine AS BUILD
WORKDIR /BUILD
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=BUILD /BUILD/dist /usr/share/nginx/html
EXPOSE 80

